### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by vanhumbeecka** [campoy/justforfunc#14]
halfway through the video, I build the docker image through the makefile, which works,
but when i try to run ```docker run -p 8080:8080 campoy/say``` I get an error.

```
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

It seems he can't find the entrypoint of the dockerfile or something.
I get this error on the latest docker version (ce).
Before I upgraded my docker version, i got almost the same error, but there, the message explicitly pointed to the "/app" that was not found.

Any suggestions?
I'm on ubuntu 16.04

_Update_
I Tested this with the source code of this github project itself.
Same error, Maybe an OS issue?

**Comment by campoy** [comment]
Hard to see without any of your code, unfortunately.
It might be because you're missing either the binary, or some of the libraries that it depends on.

**Comment by vanhumbeecka** [comment]
I also tried it with this repo itself, without modifications, and still no luck on ubuntu.
It's possible it has something to do with missing binaries, but I don't know for sure. The error message is just unclear.

FYI, the part that DID work on ubuntu was where the docker image directly executed the flite command (with exec.Command), but it stopped working with the new code (backend service - which is also the final code in this repo)

Tried it again wit Mac OS X Sierra, now it does work.
So I'm not going to spend more time on this issue myself :)

**Comment by najamsk** [comment]
in 2019 i am having same issue. :( how can we miss a binary as go package everything in one executable? when i invoke binary it works and print listening on port 8080 and when i try to run client manually by go run say.go it says not implemented error. 

but when i try with docker get this exec standard_init_linux.go:211: exec user process caused "no such file or directory"

**Comment by najamsk** [comment]
i have uploaded code at https://github.com/najamsk/text2speechrepo

**Comment by najamsk** [comment]
i have checked every file and made sure that end of file is LF. also ldd on generated app binary revealed its dynamic linked file. 

`ldd app`

i have change backend makefile script to following and it now generates static linked binary with no dependencies. 

```
build:
	GOOS=linux CGO_ENABLED=0 go build -o app
	docker build -t campoy/say .
	rm -f app
```
