### ISSUE TITLE
suggest: simple mobile app to exchange public keys via qrcode

### ISSUE THREAD

**Issue by mh-cbon** [campoy/justforfunc#17]
Hi,

I d like to suggest an app for future videos.

An app that runs on mobile, consume video feed to detect and read a qrcode, on the other end, the app can create/manage gpg identities in order to shows their public keys as a qrcode on the screen, so that another user can read it and decode the public key, you see ?

For the qrcode, i know there are several golang libs.
For the public keys, that be cool to introduce golang crypto https://godoc.org/golang.org/x/crypto/ and more specifically maybe https://godoc.org/golang.org/x/crypto/openpgp

For the mobile app, many things,
- is it cross compatible ios/android
- how to do/work in general
- how to interact with the video camera of the device

I have no idea if it is feasible, what do you think about it ?

Do i have to sign cla for suggestions too ? =)

**Comment by campoy** [comment]
please propose this through form.justforfunc.com

thanks!
