### ISSUE TITLE
episode 40 csvql describe

### ISSUE THREAD

**Issue by gcstang** [campoy/justforfunc#89]
after building this out, I tried to run 'desc cities' or 'desc people' like in your part 1 video and get the error

`ERROR 1105 (HY000): unknown error: unsupported syntax: &sqlparser.OtherRead{}`

**Comment by ricardoseriani** [comment]
If you try to run the full command `describe table cities` it should work.
I don't know, but I think that is the way that `gopkg.in/src-d/go-mysql-server.v0` is implemented.

**Comment by gcstang** [comment]
Thank you
