### ISSUE TITLE
Is it ok to use new context in client code?

### ISSUE THREAD

**Issue by vbauerster** [campoy/justforfunc#9]
Hi Francesc!
In your talk, you're saying that gRPC still using old context path.
But in the client [code](https://github.com/campoy/justforfunc/blob/c2447c446c26871401e9950fb1db88ecf6c2cd29/12-say-grpc/say/main.go#L17), new context path is actually used.
So my question is it ok to use new context path with gRPC?

**Comment by campoy** [comment]
I use the new one because I can 😄 
I'm passing values that satisfy the `context.Context` interface anyway, no matter how they were created.
If this was for a library I would consider backwards compatibility etc, but for client it seems safe enough
